apiVersion: "kafka.jikkou.io/v1"
kind: KafkaTopic
metadata:
  name: 'foo'
  labels:
    environment: 'development'
    owner: 'florian'
    managed-by: kestra
    execution-id: '4NcbiwBQUYC9iCjS96kcuv'
spec:
  partitions: 10
  replicas: 10
  configs:
    retention.ms: 172800000
    cleanup.policy: 'delete'
