apiVersion: "kafka.jikkou.io/v1"
kind: KafkaTopic
metadata:
  name: 'gfdsg'
  labels:
    environment: 'development'
    owner: 'gfdsgdsf'
    managed-by: kestra
    execution-id: '3iV1PHEQt8V0dvZrLDp5R'
spec:
  partitions: 6
  replicas: 3
  configs:
    retention.ms: 172800000
    cleanup.policy: 'delete'
