apiVersion: "kafka.jikkou.io/v1"
kind: KafkaTopic
metadata:
  name: 'gfdssg'
  labels:
    environment: 'development'
    owner: 'gdfsgsf'
    managed-by: kestra
    execution-id: '5csvhBR0TzgTO1lkmlNtc3'
spec:
  partitions: 6
  replicas: 3
  configs:
    retention.ms: 172800000
    cleanup.policy: 'delete'
