apiVersion: "kafka.jikkou.io/v1"
kind: KafkaTopic
metadata:
  name: 'my-first-topic'
  labels:
    environment: 'development'
    owner: 'Florian'
    managed-by: kestra
    execution-id: '5x1wde3j6zZPJY0b8iHHzK'
spec:
  partitions: 10
  replicas: 10
  configs:
    retention.ms: 172800000
    cleanup.policy: 'delete'
